### ISSUE TITLE
com.google.android.gms:play-services-location:11.6.0, but version 11.6.2 

### ISSUE THREAD

**Issue by vijayb** [dpa99c/cordova-android-play-services-gradle-release#7] opened 2018-02-09 19:23 UTC
Hi Dave, thanks for trying to fix this issue. Unfortunately when using your plugin I'm still facing the dreaded dependency hell. Here's the stack trace I get when doing cordova build android:

Found com.google.android.gms:play-services-location:11.6.0, but version 11.6.2 is needed for the google-services plugin.
:processReleaseGoogleServices FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processReleaseGoogleServices'.
> Please fix the version conflict either by updating the version of the google-services plugin (information about the latest version is available at https://bintray.com/android/android-tools/com.google.gms.google-services/) or updating the version of com.google.android.gms to 11.6.2.

Here's my plugins:

cordova plugins list
cordova-android-play-services-gradle-release 1.2.0 "cordova-android-play-services-gradle-release"
cordova-background-geolocation 2.10.1 "BackgroundGeolocation"
cordova-google-api-version 0.0.1 "cordova-google-api-version"
cordova-plugin-actionsheet 2.3.3 "ActionSheet"
cordova-plugin-background-fetch 5.2.1 "CDVBackgroundFetch"
cordova-plugin-cocoalumberjack 0.0.4 "CocoaLumberjack"
cordova-plugin-console 1.1.0 "Console"
cordova-plugin-device 1.1.7 "Device"
cordova-plugin-dialogs 1.3.4 "Notification"
cordova-plugin-ionic 3.1.2 "IonicCordova"
cordova-plugin-splashscreen 5.0.2 "Splashscreen"
cordova-plugin-statusbar 2.4.2-dev "StatusBar"
cordova-plugin-whitelist 1.3.3 "Whitelist"
ionic-plugin-deeplinks 1.0.15 "Ionic Deeplink Plugin"
phonegap-plugin-push 2.1.3 "PushPlugin"
uk.co.workingedge.phonegap.plugin.launchnavigator 4.1.3 "Launch Navigator"

Let me know if there's any extra information I can provide that might help.

**Comment by dpa99c** [comment] 2018-02-09 20:27
Firstly, you don't need to include this plugin in your project since you have [cordova-google-api-version](https://github.com/transistorsoft/cordova-google-api-version) in it:
this plugin explicitly [attempts to override](https://github.com/dpa99c/cordova-android-play-services-gradle-release/blob/master/cordova-android-play-services-gradle-release.gradle#L15) the Gradle package `com.google.android.gms` while `cordova-google-api-version` [attempts to override](https://github.com/transistorsoft/cordova-google-api-version/blob/master/cordova-google-api-version.gradle#L15) both `com.google.android.gms` _and_ `com.google.firebase`.

However, that's not the cause of your problem. The cause is `phonegap-plugin-push` since it [uses a Gradle class instead of a string](https://github.com/phonegap/phonegap-plugin-push/blob/master/push.gradle#L35) to include the `GoogleServicesPlugin` which leads to pulling in a different version of `com.google.android.gms` in a way which this plugin (and `cordova-google-api-version`) are unable to override. See [this discussion](https://github.com/dpa99c/cordova-plugin-request-location-accuracy/issues/35#issuecomment-325690966) for more info. 

So your best bet is to attempt to use either this plugin or `cordova-google-api-version` to set the align the version to `11.6.2` as required by the Google Services Plugin since it's not possible to override it to another version (without the build failing).

**Comment by vijayb** [comment] 2018-02-09 20:28
Thank you for the quick reply and help. I'll give your suggestion a go and report back.

**Comment by vijayb** [comment] 2018-02-09 20:36
Btw does this mean I need to completely remove the push plugin?

**Comment by vijayb** [comment] 2018-02-09 20:45
I didn't remove the push plugin and tried to use your plugin to pin to 11.6.2 and get this build error:

1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
+-----------------------------------------------------------------
| cordova-android-play-services-gradle-release: 11.+
+-----------------------------------------------------------------
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.
Failed to notify ProjectEvaluationListener.afterEvaluate(), but primary configuration failure takes precedence.
java.lang.IllegalStateException: compileSdkVersion is not specified.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:456)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:590)
	at com.android.build.gradle.BasePlugin.lambda$null$3(BasePlugin.java:555)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
	at com.android.build.gradle.BasePlugin.lambda$createTasks$4(BasePlugin.java:551)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy23.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:75)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:69)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.access$100(LifecycleProjectEvaluator.java:33)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$ConfigureProject.run(LifecycleProjectEvaluator.java:103)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:49)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:651)
	at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:133)
	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
	at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:62)
	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
	at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:246)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.initialization.DefaultGradleLauncher.configureBuild(DefaultGradleLauncher.java:165)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:124)
	at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:107)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:78)
	at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:75)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
	at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:100)
	at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:75)

	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:45)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:29)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
	at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:71)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:51)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
	at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
	at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:64)
	at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:29)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
	at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:58)
	at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:33)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)

FAILURE: Build failed with an exception.

* Where:
Script '/Users/vijayboyapati/branches/peach-delivery-app/platforms/android/cordova-google-api-version/ionicpeachdelivery-cordova-google-api-version.gradle' line: 11

* What went wrong:
A problem occurred evaluating script.
> Could not read script '/Users/vijayboyapati/branches/peach-delivery-app/platforms/android/app/cordova-google-api-version/properties.gradle' as it does not exist.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by dpa99c** [comment] 2018-02-09 20:50
Something has gone wrong with the Android platform project:

    java.lang.IllegalStateException: compileSdkVersion is not specified.

Try removing/re-adding the platform and rebuilding:

    cordova platform rm android --nosave && cordova platform add android --nosave

> Btw does this mean I need to completely remove the push plugin?

That is the cause of your problems. You may be able to manually resolve the problem by editing the `build.gradle` but this plugin cannot override the `com.google.android.gms` package version while `phonegap-plugin-push` is present in the project.

**Comment by vijayb** [comment] 2018-02-09 21:11
Hmm. So I removed your plugin, removed the push plugin, removed the android platform then re-added it and tried to build but it failed again with:

* Where:
Script '/Users/vijayboyapati/branches/peach-delivery-app/platforms/android/cordova-google-api-version/ionicpeachdelivery-cordova-google-api-version.gradle' line: 11

* What went wrong:
A problem occurred evaluating script.
> Could not read script '/Users/vijayboyapati/branches/peach-delivery-app/platforms/android/app/cordova-google-api-version/properties.gradle' as it does not exist.



I feel like I must be missing some other crucial thing

**Comment by vijayb** [comment] 2018-02-09 21:15
I tried another strategy: 

cordova plugins rm cordova-google-api-version
cordova plugin add cordova-android-play-services-gradle-release  --variable PLAY_SERVICES_VERSION=11.6.2

cordova platform rm android; cordova platform add android; ionic cordova build android --release

Now I get a different error:

Download https://maven.google.com/com/google/android/gms/play-services-basement-license/11.8.0/play-services-basement-license-11.8.0.pom

Download https://maven.google.com/com/google/android/gms/play-services-tasks-license/maven-metadata.xml
Download https://maven.google.com/com/google/android/gms/play-services-tasks-license/11.8.0/play-services-tasks-license-11.8.0.pom

:app:preReleaseBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> Could not find :tsbackgroundfetch:.
  Searched in the following locations:
      file:/Users/vijayboyapati/Library/Android/sdk/extras/m2repository//tsbackgroundfetch//tsbackgroundfetch-.pom
      file:/Users/vijayboyapati/Library/Android/sdk/extras/m2repository//tsbackgroundfetch//tsbackgroundfetch-.aar
      file:/Users/vijayboyapati/Library/Android/sdk/extras/google/m2repository//tsbackgroundfetch//tsbackgroundfetch-.pom
      file:/Users/vijayboyapati/Library/Android/sdk/extras/google/m2repository//tsbackgroundfetch//tsbackgroundfetch-.aar
      file:/Users/vijayboyapati/Library/Android/sdk/extras/android/m2repository//tsbackgroundfetch//tsbackgroundfetch-.pom
      file:/Users/vijayboyapati/Library/Android/sdk/extras/android/m2repository//tsbackgroundfetch//tsbackgroundfetch-.aar
      https://jcenter.bintray.com//tsbackgroundfetch//tsbackgroundfetch-.pom
      https://jcenter.bintray.com//tsbackgroundfetch//tsbackgroundfetch-.aar
      https://maven.google.com//tsbackgroundfetch//tsbackgroundfetch-.pom
      https://maven.google.com//tsbackgroundfetch//tsbackgroundfetch-.aar
      https://repo1.maven.org/maven2//tsbackgroundfetch//tsbackgroundfetch-.pom
      https://repo1.maven.org/maven2//tsbackgroundfetch//tsbackgroundfetch-.aar
      file:/Users/vijayboyapati/branches/peach-delivery-app/platforms/android/app/src/android/libs/tsbackgroundfetch-.aar
      file:/Users/vijayboyapati/branches/peach-delivery-app/platforms/android/app/src/android/libs/tsbackgroundfetch.aar
  Required by:
      project :app
> Could not find :tslocationmanager:.
  Searched in the following locations:
      file:/Users/vijayboyapati/Library/Android/sdk/extras/m2repository//tslocationmanager//tslocationmanager-.pom
      file:/Users/vijayboyapati/Library/Android/sdk/extras/m2repository//tslocationmanager//tslocationmanager-.aar
      file:/Users/vijayboyapati/Library/Android/sdk/extras/google/m2repository//tslocationmanager//tslocationmanager-.pom
      file:/Users/vijayboyapati/Library/Android/sdk/extras/google/m2repository//tslocationmanager//tslocationmanager-.aar
      file:/Users/vijayboyapati/Library/Android/sdk/extras/android/m2repository//tslocationmanager//tslocationmanager-.pom
      file:/Users/vijayboyapati/Library/Android/sdk/extras/android/m2repository//tslocationmanager//tslocationmanager-.aar
      https://jcenter.bintray.com//tslocationmanager//tslocationmanager-.pom
      https://jcenter.bintray.com//tslocationmanager//tslocationmanager-.aar
      https://maven.google.com//tslocationmanager//tslocationmanager-.pom
      https://maven.google.com//tslocationmanager//tslocationmanager-.aar
      https://repo1.maven.org/maven2//tslocationmanager//tslocationmanager-.pom
      https://repo1.maven.org/maven2//tslocationmanager//tslocationmanager-.aar
      file:/Users/vijayboyapati/branches/peach-delivery-app/platforms/android/app/src/android/libs/tslocationmanager-.aar
      file:/Users/vijayboyapati/branches/peach-delivery-app/platforms/android/app/src/android/libs/tslocationmanager.aar
  Required by:
      project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
11 actionable tasks: 11 executed

**Comment by dpa99c** [comment] 2018-02-09 21:20
Those errors are something to do with `cordova-background-geolocation` and `cordova-plugin-background-fetch` which are both TransistorSoft plugins, hence the `ts` prefix.

Any time you change the Gradle configuration (e.g. removing this or other Gradle-related plugins), you should re-move and re-add the Android platform to rebuild the `build.gradle` file.

**Comment by dpa99c** [comment] 2018-02-16 08:11
Closing this as the most recently posted errors do not relate to this plugin

**Closed as completed by dpa99c** 2018-02-16 08:11 UTC

**Comment by guilhermefilippo** [comment] 2018-11-12 20:29
> I tried another strategy:
> 
> cordova plugins rm cordova-google-api-version
> cordova plugin add cordova-android-play-services-gradle-release --variable PLAY_SERVICES_VERSION=11.6.2
> 
> cordova platform rm android; cordova platform add android; ionic cordova build android --release
> 
> Now I get a different error:
> 
> Download https://maven.google.com/com/google/android/gms/play-services-basement-license/11.8.0/play-services-basement-license-11.8.0.pom
> 
> Download https://maven.google.com/com/google/android/gms/play-services-tasks-license/maven-metadata.xml
> Download https://maven.google.com/com/google/android/gms/play-services-tasks-license/11.8.0/play-services-tasks-license-11.8.0.pom
> 
> :app:preReleaseBuild FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Could not resolve all files for configuration ':app:releaseCompileClasspath'.
> 
> > Could not find :tsbackgroundfetch:.
> > Searched in the following locations:
> > file:/Users/vijayboyapati/Library/Android/sdk/extras/m2repository//tsbackgroundfetch//tsbackgroundfetch-.pom
> > file:/Users/vijayboyapati/Library/Android/sdk/extras/m2repository//tsbackgroundfetch//tsbackgroundfetch-.aar
> > file:/Users/vijayboyapati/Library/Android/sdk/extras/google/m2repository//tsbackgroundfetch//tsbackgroundfetch-.pom
> > file:/Users/vijayboyapati/Library/Android/sdk/extras/google/m2repository//tsbackgroundfetch//tsbackgroundfetch-.aar
> > file:/Users/vijayboyapati/Library/Android/sdk/extras/android/m2repository//tsbackgroundfetch//tsbackgroundfetch-.pom
> > file:/Users/vijayboyapati/Library/Android/sdk/extras/android/m2repository//tsbackgroundfetch//tsbackgroundfetch-.aar
> > https://jcenter.bintray.com//tsbackgroundfetch//tsbackgroundfetch-.pom
> > https://jcenter.bintray.com//tsbackgroundfetch//tsbackgroundfetch-.aar
> > https://maven.google.com//tsbackgroundfetch//tsbackgroundfetch-.pom
> > https://maven.google.com//tsbackgroundfetch//tsbackgroundfetch-.aar
> > https://repo1.maven.org/maven2//tsbackgroundfetch//tsbackgroundfetch-.pom
> > https://repo1.maven.org/maven2//tsbackgroundfetch//tsbackgroundfetch-.aar
> > file:/Users/vijayboyapati/branches/peach-delivery-app/platforms/android/app/src/android/libs/tsbackgroundfetch-.aar
> > file:/Users/vijayboyapati/branches/peach-delivery-app/platforms/android/app/src/android/libs/tsbackgroundfetch.aar
> > Required by:
> > project :app
> > Could not find :tslocationmanager:.
> > Searched in the following locations:
> > file:/Users/vijayboyapati/Library/Android/sdk/extras/m2repository//tslocationmanager//tslocationmanager-.pom
> > file:/Users/vijayboyapati/Library/Android/sdk/extras/m2repository//tslocationmanager//tslocationmanager-.aar
> > file:/Users/vijayboyapati/Library/Android/sdk/extras/google/m2repository//tslocationmanager//tslocationmanager-.pom
> > file:/Users/vijayboyapati/Library/Android/sdk/extras/google/m2repository//tslocationmanager//tslocationmanager-.aar
> > file:/Users/vijayboyapati/Library/Android/sdk/extras/android/m2repository//tslocationmanager//tslocationmanager-.pom
> > file:/Users/vijayboyapati/Library/Android/sdk/extras/android/m2repository//tslocationmanager//tslocationmanager-.aar
> > https://jcenter.bintray.com//tslocationmanager//tslocationmanager-.pom
> > https://jcenter.bintray.com//tslocationmanager//tslocationmanager-.aar
> > https://maven.google.com//tslocationmanager//tslocationmanager-.pom
> > https://maven.google.com//tslocationmanager//tslocationmanager-.aar
> > https://repo1.maven.org/maven2//tslocationmanager//tslocationmanager-.pom
> > https://repo1.maven.org/maven2//tslocationmanager//tslocationmanager-.aar
> > file:/Users/vijayboyapati/branches/peach-delivery-app/platforms/android/app/src/android/libs/tslocationmanager-.aar
> > file:/Users/vijayboyapati/branches/peach-delivery-app/platforms/android/app/src/android/libs/tslocationmanager.aar
> > Required by:
> > project :app
> 
> * Try:
>   Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 4s
> 11 actionable tasks: 11 executed

Works for me... thanks
